import { useState } from "react";
import { Code, Play, RotateCcw, CheckCircle, ArrowLeft } from "lucide-react";
import { ProblemPanel } from "./components/ProblemPanel";
import { EditorPanel } from "./components/EditorPanel";
import { usePuterAI } from "./hooks/usePuterAI";
import { useLocalStorage } from "./hooks/useLocalStorage.js";
import { DIFFICULTIES, INITIAL_CODE, PROMPTS } from "./utils/constants.js";

function App() {
  const { ready: aiReady, chat } = usePuterAI();

  const [questionData, setQuestionData] = useLocalStorage(
    "question:data",
    null,
    { parse: true }
  );
  const [code, setCode] = useLocalStorage(
    "editor:code",
    INITIAL_CODE,
    { parse: false }
  );
  const [feedback, setFeedback] = useLocalStorage(
    "feedback",
    "",
    { parse: false }
  );
  const [difficulty, setDifficulty] = useLocalStorage(
    "difficulty",
    "",
    { parse: false }
  );
  const [loading, setLoading] = useState(false);
  const [warning, setWarning] = useState("");

  const handleDifficultySelect = (level) => {
    setDifficulty(level);
    if (warning) setWarning("");
  };

  const generateQuestion = async () => {
    if (!DIFFICULTIES.includes(difficulty)) {
      setWarning(
        "⚠️ Please select a difficulty level before generating a question."
      );
      return;
    }

    setWarning("");
    setLoading(true);
    setFeedback("");
    setCode(INITIAL_CODE);
    setQuestionData(null);

    try {
      const reply = await chat(PROMPTS.question(difficulty));
      const parsed = JSON.parse(reply);
      setQuestionData(parsed);
    } catch (error) {
      setFeedback(`⛔ Error: ${error.message}`);
    }
    setLoading(false);
  };

  const checkSolution = async () => {
    if (!code.trim()) return;
    setLoading(true);
    try {
      const reply = await chat(PROMPTS.review(questionData?.problem, code));
      setFeedback(reply);
    } catch (error) {
      setFeedback(`⛔ Error: ${error.message}`);
    }
    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-gray-900 to-slate-800 flex flex-col items-center justify-center p-6 gap-10">
      <h1 className="text-6xl sm:text-8xl font-bold bg-gradient-to-r from-sky-400 via-blue-300 to-indigo-400 bg-clip-text text-transparent text-center">
        CodeCoach
      </h1>
      <div className="w-full max-w-7xl flex flex-col items-center justify-center">
        {!questionData ? (
          <div className="w-full max-w-md p-10 bg-gray-900/80 backdrop-blur-md border border-gray-700 rounded-3xl shadow-lg shadow-sky-600 hover:shadow-2xl hover:shadow-sky-400 transition duration-300 text-center">
            <Code className="mx-auto mb-6 text-cyan-400 w-24 h-24" />
            <h2 className="text-3xl font-semibold text-white mb-4">
              Ready to Practice?
            </h2>
            <p className="text-slate-300 mb-8 text-lg leading-relaxed">
              Solve coding interview questions generated by AI, get hints, and
              improve your skills!
            </p>
            <div className="mb-8">
              <p className="text-sky-400 mb-4 text-lg font-semibold text-left">
                Select Difficulty:
              </p>
              <div className="flex justify-center gap-3 flex-wrap sm:flex-wrap">
                {DIFFICULTIES.map((level) => (
                  <button
                    key={level}
                    onClick={() => handleDifficultySelect(level)}
                    className={`px-6 py-3 rounded-full font-semibold transition-colors duration-200 cursor-pointer ${
                      difficulty === level
                        ? "bg-blue-500 text-white shadow-md"
                        : "bg-gray-700 text-gray-300 hover:bg-gray-600"
                    }`}
                  >
                    {level}
                  </button>
                ))}
              </div>
            </div>
            {warning && (
              <p className="text-red-500 font-semibold mb-4">{warning}</p>
            )}

            <button
              onClick={generateQuestion}
              disabled={!aiReady || loading}
              className="w-full px-10 py-4 bg-gradient-to-r from-sky-400 to-emerald-400 hover:from-sky-500 hover:to-emerald-500 text-white
              font-semibold text-lg rounded-3xl shadow-lg transition duration-300 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
            >
              {loading ? "Generating..." : "Generate Question"}
            </button>
          </div>
        ) : (
          <div className="space-y-6 w-full">
            <div className="grid lg:grid-cols-2 gap-6">
              <ProblemPanel data={questionData} />
              <EditorPanel code={code} onChange={setCode} />
            </div>

            <div className="flex gap-6 lg:gap-10 justify-center items-center flex-col lg:flex-row">
              <div className="flex flex-wrap gap-3 justify-center items-center">
                <button
                  onClick={checkSolution}
                  disabled={loading || !aiReady || !code.trim()}
                  className="px-6 py-3 bg-gradient-to-r from-blue-500 to-emerald-500 hover:opacity-80 text-white font-semibold rounded-2xl transition-all duration-300 disabled:opacity-50 flex items-center justify-center gap-2 cursor-pointer"
                >
                  <Play className="w-5 h-5" />
                  {loading ? "Checking..." : "Check solution"}
                </button>

                <button
                  onClick={generateQuestion}
                  disabled={loading || !aiReady}
                  className="px-6 py-3 bg-gradient-to-r from-purple-500 to-pink-500 hover:opacity-80 text-white font-semibold rounded-2xl transition-all duration-300 disabled:opacity-50 flex items-center justify-center gap-2 cursor-pointer"
                >
                  <RotateCcw className="w-5 h-5" />
                  {loading ? "Generating..." : "New Question"}
                </button>

                <button
                  onClick={() => {
                    setQuestionData(null);
                    setCode(INITIAL_CODE);
                    setFeedback("");
                    setLoading(false);
                    setWarning("");
                    setDifficulty("");
                  }}
                  disabled={loading}
                  className="px-6 py-3 bg-gradient-to-r from-red-500 to-amber-500 hover:opacity-80 text-white font-semibold rounded-2xl transition-all duration-300 disabled:opacity-50 flex items-center justify-center gap-2 cursor-pointer"
                >
                  <ArrowLeft className="w-5 h-5" />
                  Go Back
                </button>
              </div>

              <div className="flex gap-3 items-center flex-wrap">
                <p className="text-slate-300 font-semibold">Difficulty: </p>
                {DIFFICULTIES.map((level) => (
                  <button
                    key={level}
                    onClick={() => handleDifficultySelect(level)}
                    className={`px-4 py-2 rounded-full font-semibold transition-colors duration-200 cursor-pointer ${
                      difficulty === level
                        ? "bg-blue-500 text-white shadow-md"
                        : "bg-gray-700 text-gray-300 hover:bg-gray-600"
                    }`}
                  >
                    {level}
                  </button>
                ))}
              </div>
            </div>

            {feedback && (
              <div
                role="status"
                aria-live="polite"
                className={`
                  rounded-3xl p-6 shadow-2xl backdrop-blur-sm ${
                    feedback.includes("✅")
                      ? "bg-green-900/40 border border-green-500/30"
                      : feedback.includes("⛔")
                      ? "bg-red-900/40 border border-red-500/30"
                      : "bg-gray-800/60 border border-gray-700/50"
                  }
              `}
              >
                <div className="flex items-start gap-4">
                  <CheckCircle
                    className={`w-6 h-6 ${
                      feedback.includes("✅")
                        ? "text-green-400"
                        : feedback.includes("⛔")
                        ? "text-red-400"
                        : "text-blue-400"
                    }`}
                  />
                  <div className="flex-1 text-gray-200 whitespace-pre-wrap leading-relaxed">
                    {feedback}
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default App;
